controller_joint_names: ['', 'right1', 'right11', 'right12', 'right2', 'right21', 'right22', 'right3', 'right31', 'right32', 'left3', 'left31', 'left32', 'left2', 'left21', 'left22', 'left1', 'left11', 'left12', ]
